#!/bin/sh

. colors.sh

answers="
It is certain\n
It is decidedly so\n
Without a doubt\n
Yes definitely\n
You may rely on it\n
As I see it, yes\n
Most likely\n
Outlook good\n
Yes\n
Signs point to yes\n
Reply hazy try again\n
Ask again later\n
Better not tell you now\n
Cannot predict now\n
Concentrate and ask again\n
Don't count on it\n
My reply is no\n
My sources say no\n
Outlook not so good
Very doubtful"


echo $SOL_red


printf '
Welcome to MYYYYYYY magic8ball thingy
enter ur question below!
'

while true; do
  echo -n '>'
  read question
echo $answers | sort -R | head -1
done

