#!/bin/sh

echo ${SOL_clear}

echo ${SOL_yellow}"Who would cross the Bridge of Death
Must answer me these questions three
'Ere the other side he see"
die()
{
  echo "${SOL_red}"You DIED"
}

live()
{
  echo "${SOL_yellow}"You May See The Other Side!"
}

ask()
{
  question="$1"
  color="$2"
  echo $color$question$SOL_reset
  printf '> '
  read answer
  answer=`echo $answer | tr '[:upper:]' '[:lower:]'`
}

ask  ${SOL_red}"What is your name?"
echo ${SOL_green}
name=$answer

ask ${SOL_red}"What is your quest?"
echo ${SOL_green}
quest=$answer


if [ "$name" = "lancelot" -o "$name" = "galahad" ]; then
  ask ${SOL_red}"What is your favorite color?"
  colour=$answer
  echo ${SOL_reset}

elif [ "$name" = "king arthur" ]; then
  ask ${SOL_green}"What is the airspeed velocity of an unlegged 
  swallow?"

  if [ "$answer" = "depends on if it's an african or europian swallow" ]; then
    live
    echo ${SOL_green}

elif [ "$name" = "sir robin" ]; then
  echo ${SOL_green}"What is the capitol of acidia?"
  if [ "$answer" = "I dont know that" ]; then
    
    die
    
    echo ${SOL_green}
  
  echo "${SOL_red}> ${SOL_red}"
  fi
fi
fi
